"""T4: E1 exact-model verification gates (booktabs table).

Reads the per-part e1 result files (seed 42) and emits
figures/T4_e1_gates.tex. Every number comes from the JSON files.
"""
import json

from _style import RESULTS, FIGDIR


def load(part):
    return json.loads((RESULTS / "e1" / f"e1_{part}_seed42.json").read_text())


def main():
    a, b, c, d, e, f = (load(p) for p in "abcdef")
    eta = a["eta"]
    thr_ratio = b["fitted_threshold"] / (eta / 2.0)
    n_cells_d = len(d["rows"])
    n_p90 = sum(r["p90_risk_ratio"] * r["risk_star"]
                <= 3.0 * d["log_Tmax"] * r["risk_star"] + d["eps_additive"]
                for r in d["rows"])
    n_safe = sum(r["safe_vs_frozen"] for r in d["rows"] if r["t_star"] > 0)
    n_pos = sum(1 for r in d["rows"] if r["t_star"] > 0)
    gain_a0 = e["mean_relgain_by_alpha"]["0.0"]
    gain_a1 = e["mean_relgain_by_alpha"]["1.0"]

    rows = [
        ("(a) risk-curve identity",
         r"$\sup_t |\hat E(t)-E(t)|/E(t)$ over 30 cells",
         f"{a['worst_rel_err']:.3f}", r"$< 0.05$",
         "pass" if a["gate_pass"] else "FAIL"),
        ("(b) phase boundary",
         r"held-out sign accuracy of $\alpha^2\delta^2/\sigma^2 \gtrless \eta/2$",
         f"{b['holdout_accuracy']:.2f}", r"$\geq 0.95$",
         "pass" if b["gate_pass"] else "FAIL"),
        ("", r"fitted / theoretical threshold",
         f"{thr_ratio:.3f}", r"$\approx 1$", "---"),
        ("(c) optimal stopping",
         r"fraction of cells with risk at $\hat t_{\rm emp}$ within 5\% of $E(t^*)$",
         f"{c['frac_risk_within_5pct']:.2f}", r"$\geq 0.90$",
         "pass" if c["gate_pass"] else "FAIL"),
        ("(d) ALTA diagnostic (thm-shaped)",
         r"cells with p90 risk $\leq 3\log T\, E(t^*) + 2\eta\sigma^2$",
         f"{n_p90}/{n_cells_d}", f"{n_cells_d}/{n_cells_d}",
         "pass" if d["p90_gate"] else "FAIL"),
        ("", r"cells ($t^*>0$) with mean risk $\leq$ frozen",
         f"{n_safe}/{n_pos}", f"{n_pos}/{n_pos}",
         "pass" if d["safety_gate"] else "FAIL"),
        ("(e) nonconvex ReLU",
         r"mean rel.\ gain monotone in $\alpha$; harm at $\alpha=0$",
         f"{gain_a0:.2f} at $\\alpha{{=}}0$ vs "
         f"{gain_a1:.2f} at $\\alpha{{=}}1$",
         "monotone", "pass" if e["gate_pass"] else "FAIL"),
        ("(f) batch scaling",
         r"max rel.\ err of $\min_t E_N(t)$ vs theory over $N\in\{1..64\}$",
         f"{f['max_rel_err']:.4f}", r"$< 0.1$",
         "pass" if f["gate_pass"] else "FAIL"),
    ]

    lines = [
        "% Auto-generated by figures/scripts/tab_T4.py from",
        "% experiments/results/e1/e1_{a..f}_seed42.json -- do not edit.",
        r"\begin{tabular}{@{}llccc@{}}",
        r"\toprule",
        r"Part & Quantity (gate criterion) & Value & Gate & Result \\",
        r"\midrule",
    ]
    for part, desc, val, gate, res in rows:
        lines.append(rf"{part} & {desc} & {val} & {gate} & {res} \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = FIGDIR / "T4_e1_gates.tex"
    out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
