"""T2: full E3 ImageNet-C results table (longtable, appendix).

One row per (corruption, severity, method): frozen / bn0 / best fixed step
(with argmax step) / ALTA accuracy and ALTA mean stopping step, from the
raw e3 result files (seed 0; seeds 1-2 exist for 4 corruptions --
contrast, fog, gaussian noise and motion blur -- and match within noise;
reported in the repository, not here).

Emits figures/T2_e3_full.tex.
"""
import json

from _style import RESULTS, FIGDIR

METHODS = ["tent", "eata", "sar"]
CORRUPTIONS = [
    "gaussian_noise", "shot_noise", "impulse_noise",
    "defocus_blur", "glass_blur", "motion_blur", "zoom_blur",
    "snow", "frost", "fog", "brightness",
    "contrast", "elastic_transform", "pixelate", "jpeg_compression",
]


def cell(path, sev):
    d = json.loads(path.read_text())
    for c in d["results"]:
        if c["severity"] == sev:
            return c
    raise KeyError(f"severity {sev} not in {path}")


def main():
    lines = [
        "% Auto-generated by figures/scripts/tab_T2.py from",
        "% experiments/results/e3/<corruption>_<method>_{fixed,alta}_s0.json",
        "% -- do not edit.",
        r"\begin{longtable}{@{}llrrrrrr@{}}",
        r"\caption{Full E3 ImageNet-C results (ResNet-50, seed 0). Accuracy",
        r"in \%; ``best fixed'' is the label-selected best step count of the",
        r"fixed-step run (an oracle over step counts); ALTA is label-free.",
        r"$\bar t_{\rm ALTA}$ is ALTA's mean stopping step.}",
        r"\label{tab:T2} \\",
        r"\toprule",
        r"Corruption & Method & Sev. & Frozen & BN-0 & Best fixed (step) &"
        r" ALTA & $\bar t_{\rm ALTA}$ \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"Corruption & Method & Sev. & Frozen & BN-0 & Best fixed (step) &"
        r" ALTA & $\bar t_{\rm ALTA}$ \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
    ]
    n_stale = 0
    for corr in CORRUPTIONS:
        for m in METHODS:
            for sev in (3, 5):
                fx = cell(RESULTS / "e3" / f"{corr}_{m}_fixed_s0.json", sev)
                al = cell(RESULTS / "e3" / f"{corr}_{m}_alta_s0.json", sev)
                if not al["batches"][0].get("alta_t0_is_frozen", False):
                    n_stale += 1
                best = max(fx["acc_by_step"])
                bstep = fx["acc_by_step"].index(best)
                name = corr.replace("_", r"\_") if m == METHODS[0] and \
                    sev == 3 else ""
                lines.append(
                    rf"{name} & {m} & {sev} & {fx['frozen_acc']*100:.2f} & "
                    rf"{fx['bn0_acc']*100:.2f} & {best*100:.2f} ({bstep}) & "
                    rf"{al['adapted_acc']*100:.2f} & "
                    rf"{al['mean_t_hat']:.1f} \\")
        lines.append(r"\midrule")
    assert lines[-1] == r"\midrule"
    lines.pop()                                    # no rule before \endfoot
    lines += [r"\end{longtable}", ""]
    out = FIGDIR / "T2_e3_full.tex"
    out.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {out}; stale alta cells: {n_stale}")


if __name__ == "__main__":
    main()
