#!/usr/bin/env python
"""Supplement Table S5 -- E2 batch mechanics, generated.

WHY THIS SCRIPT EXISTS
----------------------
The two halves of the E2 batch study are scientific evidence for stated
conclusions -- the sign of the accuracy gain against batch size under the
published bn-train protocol, and the $1/N$ scaling of the per-batch SSL
gradient noise under bn-eval -- and not audit or provenance material.  They
were carried only by the release figure `F5_batch.pdf`, so a reader of the
journal documents alone could not see the evidence for a claim those
documents make.  This script puts the same two halves into the
Supplementary Material as a compact NUMERICAL table, which is what the
figure's panels are read off anyway; the figure, its caption and its
generator stay in the release as the visual form.

WHAT IT READS, AND WHY THOSE RECORDS
  (a) experiments/results/e2/cifar10_tent_batch_sweep_s0_bntrain.json
      -- the published Tent protocol, BatchNorm in TRAIN mode, seed 0.
      Per-batch frozen accuracy and per-step adapted accuracy at
      t in {1,2,5,10}; the cell is the mean over batches of
      (adapted - frozen), in accuracy points.
  (b) experiments/results/e2/cifar10_tent_batch_sweep_s{0,1,2}.json
      -- BatchNorm in EVAL mode, where per-sample gradients are not
      coupled through the batch statistics, so a dispersion measured
      there is the object the 1/N reading is about.  The cell is the
      median over batches x corruptions x seeds of
      sigma2_batch_rel * gnorm_ssl^2.  N = 1 is EXCLUDED because Tent's
      objective is deterministic there and the dispersion is exactly 0 --
      an exclusion of a degenerate cell, not of an inconvenient one, and
      it is printed in the table rather than left in this comment.

The two halves are gated separately and the table says so: BatchNorm in
train mode couples per-sample gradients through the batch statistics, so a
per-sample dispersion measured under (a)'s protocol is not the theory's
independent-noise quantity, and neither half is a test of the entropy
batch-size corollary, which fixes the sign of an expected gradient inner
product and is not an accuracy threshold.

Same contract as `tab_s4_e1_gates.py`: every value is read from a record,
nothing is typed, and `--check` is a BYTE comparison that the release
archive's verifier runs.

Usage:  python tab_s5_e2_batch.py [--out PATH] [--check]
"""
from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

HERE = Path(__file__).resolve()
ROOT = HERE.parents[3]


def _rel(p):
    try:
        return Path(p).resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return Path(p).name


RES = ROOT / "experiments" / "results" / "e2"
OUT_DEFAULT = (ROOT / "paper" / "is2" / "paper" / "figures"
               / "S5_e2_batch.tex")

BNTRAIN = "cifar10_tent_batch_sweep_s0_bntrain.json"
BNEVAL = ["cifar10_tent_batch_sweep_s0.json",
          "cifar10_tent_batch_sweep_s1.json",
          "cifar10_tent_batch_sweep_s2.json"]
STEPS = ["1", "2", "5", "10"]

HEADER = r"""% Generated by paper/is2/tools/tab_s5_e2_batch.py from
%   experiments/results/e2/cifar10_tent_batch_sweep_s0_bntrain.json   (a)
%   experiments/results/e2/cifar10_tent_batch_sweep_s{0,1,2}.json     (b)
% DO NOT EDIT BY HAND: `python tab_s5_e2_batch.py --check` fails the release
% build if this file and the records disagree.  The same two halves are drawn
% as figure F5_batch.pdf by figures/scripts/fig_F5.py in the release.
% Protocol: experiments/results/is_fresh/FRESH_RESULTS.md.
"""


def load(name):
    return json.loads((RES / name).read_text(encoding="utf-8"))


def build() -> str:
    tr = load(BNTRAIN)
    Ns = sorted({r["N"] for r in tr["results"]})
    gain = {t: {} for t in STEPS}
    for N in Ns:
        accs = {t: [] for t in STEPS}
        frozen = []
        for r in tr["results"]:
            if r["N"] != N:
                continue
            for b in r["batches"]:
                assert "steps" in b, "v2 per-step schema expected"
                frozen.append(b["frozen_acc"])
                for t in STEPS:
                    accs[t].append(b["steps"][t]["acc"])
        f = statistics.fmean(frozen)
        for t in STEPS:
            gain[t][N] = (statistics.fmean(accs[t]) - f) * 100.0

    pooled = {}
    seeds = []
    for name in BNEVAL:
        ev = load(name)
        seeds.append(ev["meta"]["argv"]["seed"])
        for r in ev["results"]:
            N = r["N"]
            if N == 1:
                continue               # deterministic objective: sigma^2 == 0
            pooled.setdefault(N, []).extend(
                b["sigma2_batch_rel"] * b["gnorm_ssl"] ** 2
                for b in r["batches"])
    Nb = sorted(pooled)
    med = {N: statistics.median(pooled[N]) for N in Nb}
    # The 1/N reading, stated as a number rather than as a reference line:
    # anchor at N = 8 as the figure does and report N * median, which is
    # constant under exact 1/N scaling.
    anchor = 8
    scaled = {N: med[N] * N / (med[anchor] * anchor) for N in Nb}

    cols = "l" + "r" * len(Ns)
    head = " & ".join([r"$N$"] + [str(N) for N in Ns])
    lines = [HEADER,
             r"\begin{tabular}{@{}" + cols + r"@{}}", r"\toprule",
             head + r" \\", r"\midrule",
             r"\multicolumn{%d}{@{}l}{\emph{(a) accuracy gain over frozen "
             r"(points), bn-train, seed 0}} \\" % (len(Ns) + 1)]
    for t in STEPS:
        cells = [f"{gain[t][N]:+.4f}" for N in Ns]
        lines.append(" & ".join([rf"$t={t}$"] + cells) + r" \\")
    lines.append(r"\addlinespace")
    lines.append(r"\multicolumn{%d}{@{}l}{\emph{(b) median per-batch SSL "
                 r"gradient dispersion $\hat\sigma^{2}_{\mathrm{batch}}$, "
                 r"bn-eval, seeds %s}} \\"
                 % (len(Ns) + 1, "/".join(str(s) for s in seeds)))
    lines.append(" & ".join(
        [r"median"] + [("---" if N not in med else f"{med[N]:.4g}")
                       for N in Ns]) + r" \\")
    lines.append(" & ".join(
        [r"$N \cdot$ median, $/\,$ its value at $N{=}8$"]
        + [("---" if N not in scaled else f"{scaled[N]:.3f}")
           for N in Ns]) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT_DEFAULT))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    body = build()
    out = Path(args.out)
    if args.check:
        have = out.read_text(encoding="utf-8") if out.exists() else ""
        if have != body:
            print(f"MISMATCH {_rel(out)} differs from the generated table; "
                  f"rerun `python tab_s5_e2_batch.py`")
            raise SystemExit(1)
        print(f"ok {_rel(out)} matches the records")
        return
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")
    print(f"wrote {_rel(out)}")


if __name__ == "__main__":
    main()
