#!/usr/bin/env python
"""Supplement Table S7 -- GPT-2 leave-one-domain-out proxy validation, generated.

WHY THIS SCRIPT EXISTS, AND WHY IT IS NOT `tab_t6_e4_proxy.py`
--------------------------------------------------------------
`experiments/ttt/is_fresh/tab_t6_e4_proxy.py` is the generator of the frozen
79-page tree's copy of this table, `paper/is/paper/figures/T6_e4_proxy.tex`.
It is a SHARED generator: its output default falls back to the is2 copy when
the frozen tree is absent, so for a while one script owned two tables in two
trees, one of which is frozen.  That arrangement has two consequences and both
were live defects.

  1. The is2 copy had already DIVERGED from what that generator produces.  The
     style campaign relabelled the table `tab:e3-proxy`, renamed the plotted
     noise quantity `\\sigma^2_{\\mathrm{rel}}` (the manuscript distinguishes
     it from the model's `\\sigma^2`, and Table 1 of the article exists to keep
     the two apart), and called the statistic the "full signed diagnostic".
     None of those edits is in the shared generator.  They survived only
     because `tab_t6_e4_proxy.py --check` compares NUMERIC TOKENS and not the
     file: a table whose every label had been rewritten passed it.  So the is2
     copy was, in the sense that matters, hand-maintained -- the exact defect
     `--check` exists to prevent, and the same one `tab_s4_e1_gates.py` was
     written to repair for the E1 gate table.

  2. The table could not be RESTRUCTURED.  It shipped inside
     `\\resizebox{\\textwidth}{!}{...}`, which scaled seven columns -- two of
     them carrying five-decimal bootstrap intervals -- down to well under the
     surrounding type size.  Fixing that means changing the column layout, and
     changing the layout in the shared generator rewrites the FROZEN tree's
     table and turns its own `--check` red.  An attempt to do it there was
     reverted in full for that reason.

This script is therefore the is2 GENERATOR OF RECORD for the table the
submission actually prints.  Its output is `S7_e4_proxy.tex`, its `--check` is
a BYTE comparison, and it is what the release archive's verifier and
`tools/gates.sh` run -- the same contract as `tab_s4_e1_gates.py` and
`tab_s5_e2_batch.py`.  `tab_t6_e4_proxy.py` is untouched and remains the
generator of the frozen tree's copy; it joins `tab_t4_e1_gates.py` in
COMMANDS.md's list of shipped scripts that produce nothing in this submission.

WHAT THE LAYOUT IS, AND WHY IT IS TWO BLOCKS
--------------------------------------------
The seven columns do not fit the supplement's 16 cm text block at the
surrounding type size, and shrinking them to fit is what produced the unreadable
table.  They are split instead, by kind, with NO column duplicated:

  (a) the frozen selection and the four held-out point correlations
      -- six narrow columns, all $\\pm 0.xxx$;
  (b) the two bootstrap intervals -- the 95% interval of $\\rho$(sel), and the
      partial Spearman of $\\delta_{v2}$ given alignment with its own interval.

The partial interval keeps FIVE decimals.  PubMed's favourable-side lower
endpoint is $+0.00044$; at three decimals it prints as $+0.000$ and reads as
"contains zero", which is the opposite of what the record says and the opposite
of the census the caption states.

EVERY VALUE AND THE CAPTION'S CENSUS ARE READ FROM THE RECORD
`experiments/results/is_fresh/f31_e4_proxy_pooled.json`: the four folds, the
frozen selection per fold, both interval pairs, and the favourable-side and
adverse-side exclusion counts with the domains that realise them.  Nothing in
the printed table is typed here except column headings.

Usage:  python tab_s7_e4_proxy.py [--out PATH] [--check]
`--check` compares against the committed .tex instead of writing it, and
exits non-zero on any difference.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve()
# .../paper/is2/tools/tab_s7_e4_proxy.py -> parents[3] is the repository root,
# both in the working tree and in an extraction of release_archive.zip.
ROOT = HERE.parents[3]


def _rel(p):
    """Repo-relative POSIX form of `p`.

    Console output from these generators is captured into archived run logs,
    so it must never carry the build machine's absolute prefix.
    """
    try:
        return Path(p).resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return Path(p).name


RES = ROOT / "experiments" / "results" / "is_fresh"
OUT_DEFAULT = (ROOT / "paper" / "is2" / "paper" / "figures"
               / "S7_e4_proxy.tex")

DOMAINS = ["code", "legal", "pubmed", "wikitext"]

HEADER = r"""% Generated by paper/is2/tools/tab_s7_e4_proxy.py from
% experiments/results/is_fresh/f31_e4_proxy_pooled.json.  This is supplement
% Table S7; DO NOT EDIT BY HAND, `python tab_s7_e4_proxy.py --check` is a BYTE
% comparison and fails the release build if you do.
% Every bracket is one 2.5/97.5 percentile pair of a single pooled 10,000-draw
% document-clustered bootstrap (5 RNG streams x B = 2000, seeds
% 20260806--20260810, pooled).  f12_e4_proxy_loo.json is the retained audit
% trail of the superseded endpoint-averaged construction; f31 replays its
% exact draws (per-stream endpoint gap 0.0) and agrees with it on both
% exclusion counts.
% The seven columns are split into two blocks rather than scaled to the text
% width: a resized single block set this table well below the surrounding type
% size.  No column appears in both blocks.
% `experiments/ttt/is_fresh/tab_t6_e4_proxy.py` generates the FROZEN tree's
% copy of this table and is not the generator of anything in this submission.
% Protocol: experiments/results/is_fresh/FRESH_RESULTS.md.
"""

# TeX-safe names for the proxy variants of the candidate menu.  The noise
# denominator is the RELATIVE per-coordinate quantity the networks are measured
# in, `\sigma^2_{\rm rel}`, and not the solvable model's `\sigma^2`: the
# article's variance map exists because reading one as the other changes what a
# statement says, and a generated table may not undo that distinction.
VARIANT_TEX = {
    "phase_v2": r"$\asgn|\asgn|\delta_{v2}/\sigma^2_{\mathrm{rel}}$",
    "phase_v2_nosigma": r"$\asgn|\asgn|\delta_{v2}$",
    "phase_v2_alpha2": r"$\asgn^2\delta_{v2}/\sigma^2_{\mathrm{rel}}$",
    "delta_v2_raw": r"$\delta_{v2}$",
    "phase_ce": r"$\asgn|\asgn|\delta_{\mathrm{ce}}/\sigma^2_{\mathrm{rel}}$",
    "phase_ce_nosigma": r"$\asgn|\asgn|\delta_{\mathrm{ce}}$",
    "delta_ce_raw": r"$\delta_{\mathrm{ce}}$",
    "frozen_ce": r"frozen CE",
    "alpha_only": r"$\asgn|\asgn|/\sigma^2_{\mathrm{rel}}$",
    "gnorm_ratio": r"$g_{\rm ssl}/g_{\rm task}$",
    "phase_v2_gnorm":
        r"$\asgn|\asgn|\delta_{v2}g_{\rm ssl}/\sigma^2_{\mathrm{rel}}$",
}


def load(name):
    return json.loads((RES / name).read_text(encoding="utf-8"))


def _iv(block, nd=3):
    return f"[${block['lo']:+.{nd}f}$, ${block['hi']:+.{nd}f}$]"


def build() -> str:
    f31 = load("f31_e4_proxy_pooled.json")
    folds, summ = f31["folds"], f31["summary"]

    # The construction must be the pooled one; a table that annotated averaged
    # endpoints as percentile intervals is exactly the defect this table is
    # part of repairing.
    assert f31["n_pooled_draws"] == 10000, f31.get("n_pooled_draws")
    assert "no averaging of endpoints" in f31["protocol"], f31["protocol"]
    assert sorted(folds) == sorted(DOMAINS), sorted(folds)

    n_pos = summ["n_folds_partial_rho_delta_v2_ci_excludes_zero"]
    n_neg = summ["n_folds_partial_rho_delta_v2_ci_excludes_zero_adverse"]
    n_folds = summ["n_folds"]
    pos = summ["folds_partial_rho_delta_v2_ci_excludes_zero_favourable"]
    neg = summ["folds_partial_rho_delta_v2_ci_excludes_zero_adverse"]

    rows_a, rows_b = [], []
    for dom in DOMAINS:
        f = folds[dom]
        rows_a.append(" & ".join([
            dom,
            VARIANT_TEX[f["selected_by_mean_rho"]],
            f"${f['heldout_rho_selected']:+.3f}$",
            f"${f['heldout_rho_phase_v2']:+.3f}$",
            f"${f['heldout_rho_alignment_only']:+.3f}$",
            f"${f['heldout_rho_difficulty_baseline_frozen_ce']:+.3f}$",
        ]) + r" \\")
        rows_b.append(" & ".join([
            dom,
            _iv(f["pooled_ci_selected"]),
            f"${f['heldout_partial_rho_delta_v2_given_alignment']:+.3f}$",
            _iv(f["pooled_ci_partial_rho_delta_v2_given_alignment"], 5),
        ]) + r" \\")

    cap = (
        r"\caption{GPT-2 leave-one-domain-out proxy validation, per domain "
        r"(GPT-2-small, 500 seed-averaged documents per held-out domain). "
        r"For each held-out domain the proxy variant maximizing mean "
        r"within-domain Spearman on the \emph{other three} domains is frozen "
        r"and scored once on the held-out domain. "
        r"\emph{(a)} the frozen selection and the four held-out "
        r"correlations: $\rho$(sel) is the held-out correlation of that "
        r"frozen selection, $\rho$(full) that of the full signed diagnostic "
        r"$\asgn|\asgn|\delta_{v2}/\sigma^2_{\mathrm{rel}}$, $\rho$(align) "
        r"that of the alignment factor alone, and $\rho$(base) that of the "
        r"frozen-cross-entropy document-difficulty baseline. "
        r"\emph{(b)} the two interval quantities, the second of which is the "
        r"partial Spearman of $\delta_{v2}$ with the gain \emph{given} the "
        r"alignment factor---the incremental contribution of the shift "
        r"proxy. The two blocks share the held-out domain and no other "
        r"column. Brackets are $95\%$ percentile pairs of one pooled "
        r"$10{,}000$-draw document-clustered bootstrap; the partial column "
        r"is printed to five decimals because PubMed's favourable-side "
        r"endpoint is resolved in the fourth. The partial "
        rf"interval excludes zero on the favourable side in {n_pos} of "
        rf"{n_folds} domains ({', '.join(pos) if pos else 'none'}) and on "
        rf"the adverse side in {n_neg} of {n_folds} "
        rf"({', '.join(neg) if neg else 'none'}): the shift proxy's "
        r"increment is resolved, but not consistently signed.}")

    lines = [HEADER,
             cap,
             r"\label{tab:e3-proxy}",
             r"",
             r"\begin{tabular}{@{}llrrrr@{}}",
             r"\toprule",
             r"\multicolumn{6}{@{}l}{\emph{(a) the frozen selection and the "
             r"four held-out correlations}} \\",
             r"\midrule",
             r"held out & selected on the other three & $\rho$(sel) & "
             r"$\rho$(full) & $\rho$(align) & $\rho$(base) \\",
             r"\midrule"]
    lines += rows_a
    lines += [r"\bottomrule",
              r"\end{tabular}",
              r"",
              r"\vspace{0.9em}",
              r"",
              r"\begin{tabular}{@{}lcrc@{}}",
              r"\toprule",
              r"\multicolumn{4}{@{}l}{\emph{(b) the two pooled "
              r"document-clustered bootstrap intervals}} \\",
              r"\midrule",
              r"& $95\%$ interval & \multicolumn{2}{c}{partial $\rho$ of "
              r"$\delta_{v2}$ given alignment} \\",
              r"\cmidrule(lr){3-4}",
              r"held out & for $\rho$(sel) & value & $95\%$ interval \\",
              r"\midrule"]
    lines += rows_b
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT_DEFAULT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    tex = build()
    if args.check:
        cur = args.out.read_text(encoding="utf-8")
        # BYTE identity, not "the same numbers in the same order".  A
        # digit-only comparison passes a table whose column LABELS, caption
        # and layout were rewritten -- which is what happened to the copy this
        # script takes over, and why it exists.
        if tex != cur:
            import difflib
            d = "\n".join(list(difflib.unified_diff(
                cur.split("\n"), tex.split("\n"),
                "committed", "generated", n=1, lineterm=""))[:40])
            raise SystemExit(
                f"the committed {_rel(args.out)} is NOT what this generator "
                f"produces from the shipped records:\n{d}")
        print(f"S7 MATCHES its generator ({_rel(args.out)})")
        return
    args.out.write_text(tex, encoding="utf-8")
    print(f"wrote {_rel(args.out)}")


if __name__ == "__main__":
    main()
