#!/usr/bin/env python
"""Table 6 -- E4 per-domain leave-one-domain-out proxy details, generated
from the records rather than typed.

WHY THIS SCRIPT EXISTS
----------------------
Section 7.4 says "per-domain details are tabulated in the appendix", so that
table has to exist and has to agree with the records; the broader E4 aggregate
table and a methodological paragraph do not discharge the pointer.  Rather
than delete the pointer or hand-type a table that goes stale the way any
hand-typed census does, the table is GENERATED here from
`f31_e4_proxy_pooled.json` and checked against the shipped `.tex` by
`--check`, exactly as `tab_t4_e1_gates.py` is.

WHAT THE COLUMNS ARE
  selected      the proxy variant chosen by mean within-domain Spearman on
                the OTHER three domains, frozen before the held-out domain is
                touched;
  rho(sel)      the held-out Spearman of that frozen selection, with its
                pooled document-clustered 95% percentile interval;
  rho(full)     the held-out Spearman of the paper's full phase statistic
                alpha|alpha| delta_v2 / sigma^2;
  rho(align)    the held-out Spearman of the alignment factor alone;
  rho(base)     the held-out Spearman of the frozen-cross-entropy
                document-difficulty baseline (which, within a domain, is the
                same rank statistic as the loss proxy);
  partial       the partial Spearman of delta_v2 with the gain GIVEN the
                alignment factor -- the incremental contribution of the shift
                proxy -- with its pooled interval.

The partial column is the one Section 7.4's revised sentence rests on: its
interval excludes zero on the favourable side in PubMed and on the ADVERSE
side in code, and contains zero in legal and WikiText.  The favourable-side
and adverse-side counts printed in the caption are read off the record, not
typed, so the "1 of 4" census cannot drift from the JSON again.

Every interval is a genuine 2.5/97.5 percentile pair of ONE pooled
10,000-draw bootstrap distribution (f31), not an average of five per-stream
percentile endpoints (f12, retained as the audit trail).

Usage:  python tab_t6_e4_proxy.py [--out PATH] [--check]
`--check` compares against the committed .tex instead of writing it.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve()
ROOT = HERE.parents[2]


def _rel(p):
    """Repo-relative POSIX form of `p`.

    Console output from these generators is captured into archived run logs,
    so it must never carry the build machine's absolute prefix.
    """
    try:
        return Path(p).resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return Path(p).name


RES = ROOT / "results" / "is_fresh"

# THE DEFAULT OUTPUT PATH MUST EXIST WHEREVER THIS SCRIPT CAN BE RUN.  It used
# to be the frozen tree's copy unconditionally.  The frozen `paper/is/` tree is
# deliberately NOT shipped in the release, so from a clean extraction the
# documented reader command
#     python experiments/ttt/is_fresh/tab_t6_e4_proxy.py --check
# died with FileNotFoundError on a path the archive does not contain -- the
# same defect class as the reconciler's, and in the same printed block of
# BUILD_ENVIRONMENT.md section 6.0.  The default now prefers the frozen copy
# when that tree is present (so the frozen tree's own build is unchanged) and
# falls back to the is2 copy, which is the one the release ships and the one
# this submission typesets.  An explicit --out still overrides both.
_FROZEN_OUT = ROOT / "paper" / "is" / "paper" / "figures" / "T6_e4_proxy.tex"
_IS2_OUT = ROOT / "paper" / "is2" / "paper" / "figures" / "T6_e4_proxy.tex"
OUT_DEFAULT = _FROZEN_OUT if _FROZEN_OUT.exists() else _IS2_OUT

DOMAINS = ["code", "legal", "pubmed", "wikitext"]
LABEL = {"code": "code", "legal": "legal", "pubmed": "pubmed",
         "wikitext": "wikitext"}

HEADER = r"""% Generated by experiments/ttt/is_fresh/tab_t6_e4_proxy.py from
% experiments/results/is_fresh/f31_e4_proxy_pooled.json.  DO NOT EDIT BY HAND:
% `python tab_t6_e4_proxy.py --check` fails the release build if this file and
% the record disagree.
% Every bracket is one 2.5/97.5 percentile pair of a single pooled 10,000-draw
% document-clustered bootstrap (5 RNG streams x B = 2000, seeds
% 20260806--20260810, pooled).  f12_e4_proxy_loo.json is the retained audit
% trail of the superseded endpoint-averaged construction; f31 replays its
% exact draws (per-stream endpoint gap 0.0) and agrees with it on both
% exclusion counts.
% Protocol: experiments/results/is_fresh/FRESH_RESULTS.md.
"""

# TeX-safe names for the proxy variants of f12's candidate menu.
VARIANT_TEX = {
    "phase_v2": r"$\asgn|\asgn|\delta_{v2}/\sigma^2$",
    "phase_v2_nosigma": r"$\asgn|\asgn|\delta_{v2}$",
    "phase_v2_alpha2": r"$\asgn^2\delta_{v2}/\sigma^2$",
    "delta_v2_raw": r"$\delta_{v2}$",
    "phase_ce": r"$\asgn|\asgn|\delta_{\mathrm{ce}}/\sigma^2$",
    "phase_ce_nosigma": r"$\asgn|\asgn|\delta_{\mathrm{ce}}$",
    "delta_ce_raw": r"$\delta_{\mathrm{ce}}$",
    "frozen_ce": r"frozen CE",
    "alpha_only": r"$\asgn|\asgn|/\sigma^2$",
    "gnorm_ratio": r"$g_{\rm ssl}/g_{\rm task}$",
    "phase_v2_gnorm": r"$\asgn|\asgn|\delta_{v2}g_{\rm ssl}/\sigma^2$",
}


def load(name):
    return json.loads((RES / name).read_text(encoding="utf-8"))


def _iv(block, nd=3):
    return f"[${block['lo']:+.{nd}f}$, ${block['hi']:+.{nd}f}$]"


def build() -> str:
    f31 = load("f31_e4_proxy_pooled.json")
    folds, summ = f31["folds"], f31["summary"]

    # The construction must be the pooled one; a table that annotated averaged
    # endpoints as percentile intervals is exactly the defect this table is
    # part of repairing.
    assert f31["n_pooled_draws"] == 10000, f31.get("n_pooled_draws")
    assert "no averaging of endpoints" in f31["protocol"], f31["protocol"]

    n_pos = summ["n_folds_partial_rho_delta_v2_ci_excludes_zero"]
    n_neg = summ["n_folds_partial_rho_delta_v2_ci_excludes_zero_adverse"]
    n_folds = summ["n_folds"]
    pos = summ["folds_partial_rho_delta_v2_ci_excludes_zero_favourable"]
    neg = summ["folds_partial_rho_delta_v2_ci_excludes_zero_adverse"]

    rows = []
    for dom in DOMAINS:
        f = folds[dom]
        sel = VARIANT_TEX[f["selected_by_mean_rho"]]
        # PubMed's favourable-side lower endpoint is +0.00044: at three
        # decimals it prints as +0.000 and would read as "contains zero",
        # which is the opposite of what the record says.  Give the partial
        # column five decimals so the exclusion is visible in the table.
        rows.append(" & ".join([
            LABEL[dom],
            sel,
            f"${f['heldout_rho_selected']:+.3f}$ "
            + _iv(f["pooled_ci_selected"]),
            f"${f['heldout_rho_phase_v2']:+.3f}$",
            f"${f['heldout_rho_alignment_only']:+.3f}$",
            f"${f['heldout_rho_difficulty_baseline_frozen_ce']:+.3f}$",
            f"${f['heldout_partial_rho_delta_v2_given_alignment']:+.3f}$ "
            + _iv(f["pooled_ci_partial_rho_delta_v2_given_alignment"], 5),
        ]) + r" \\")

    cap = (
        r"\caption{GPT-2 leave-one-domain-out proxy validation, per domain "
        r"(GPT-2-small, 500 seed-averaged documents per held-out domain). "
        r"For each held-out domain the proxy variant maximizing mean "
        r"within-domain Spearman on the \emph{other three} domains is frozen "
        r"and scored once on the held-out domain. "
        r"$\rho$(sel) is the held-out correlation of that frozen selection, "
        r"$\rho$(full) that of the full phase statistic "
        r"$\asgn|\asgn|\delta_{v2}/\sigma^2$, $\rho$(align) that of the "
        r"alignment factor alone, and $\rho$(base) that of the "
        r"frozen-cross-entropy document-difficulty baseline. The last column "
        r"is the partial Spearman of $\delta_{v2}$ with the gain "
        r"\emph{given} the alignment factor---the incremental contribution "
        r"of the shift proxy. Brackets are $95\%$ percentile pairs of one "
        r"pooled $10{,}000$-draw document-clustered bootstrap. The partial "
        rf"interval excludes zero on the favourable side in {n_pos} of "
        rf"{n_folds} domains ({', '.join(pos) if pos else 'none'}) and on "
        rf"the adverse side in {n_neg} of {n_folds} "
        rf"({', '.join(neg) if neg else 'none'}): the shift proxy's "
        r"increment is resolved, but not consistently signed.}")

    lines = [HEADER,
             cap,
             r"\label{tab:e4-proxy}",
             r"\resizebox{\textwidth}{!}{%",
             r"\begin{tabular}{@{}llllrrl@{}}",
             r"\toprule",
             r"held out & selected on the other 3 & $\rho$(sel) "
             r"[95\% interval] & $\rho$(full) & $\rho$(align) & "
             r"$\rho$(base) & partial $\rho$ of $\delta_{v2}$ given "
             r"alignment [95\% interval] \\",
             r"\midrule"]
    lines += rows
    lines += [r"\bottomrule", r"\end{tabular}}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=OUT_DEFAULT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    tex = build()
    if args.check:
        cur = args.out.read_text(encoding="utf-8")
        import re

        def nums(s):
            return re.findall(r"[-+]?\d+\.\d+|\b\d+ of \d+\b", s)
        a, b = nums(tex), nums(cur)
        print("generated:", a)
        print("committed:", b)
        if a != b:
            diff = [(i, x, y) for i, (x, y) in enumerate(zip(a, b)) if x != y]
            raise SystemExit(
                "NUMBERS DIFFER between the regenerated table and "
                f"{args.out}: {len(a)} vs {len(b)} values, first mismatches "
                f"(index, generated, committed) = {diff[:5]}"
                + ("" if len(a) == len(b) else "  [different counts]"))
        print("NUMBERS MATCH")
        return
    args.out.write_text(tex, encoding="utf-8")
    print(f"wrote {_rel(args.out)}")


if __name__ == "__main__":
    main()
